services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   
      - "15672:15672" 
    container_name: rabbitmq-general
    healthcheck:     
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:15
    container_name: products_db
    environment:
      POSTGRES_USER: fitfashion      
      POSTGRES_PASSWORD: postgres1234 
      POSTGRES_DB: fitfashion 
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data 

  # MICROSERVICIOS

  api_gateway:
    build: ./api_gateway
    restart: always
    ports:
      - "3004:3004"
    depends_on:
      - kafka
      - rabbitmq
    environment:
      - PORT=3004
      - KAFKA_BROKER=kafka:29092
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672

  ms_auth_worker:
    build: ./ms_auth
    restart: always
    depends_on:
      - kafka
    volumes:
      - ./ms_auth/db.sqlite3:/app/db.sqlite3
    environment:
      - KAFKA_BROKER=kafka:29092
      - SECRET_KEY=remivichicoke
      - DEBUG=False

  frontend:
    build: ./FrontFitFashion
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - api_gateway

  ms-products:
    build: ./ms_products  
    ports:
      - "3002:3002"
    env_file:
      - ./ms_products/.env 
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - DB_HOST=postgres         
      - DB_PORT=5432
      - DB_USERNAME=fitfashion     
      - DB_PASSWORD=postgres1234  
      - DB_DATABASE=fitfashion
    depends_on:
      rabbitmq:
        condition: service_healthy