apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-auth-deployment
  labels:
    app: ms-auth
    tier: backend
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: ms-auth
  template:
    metadata:
      labels:
        app: ms-auth
        tier: backend
    spec:
      containers:
      - name: ms-auth-container
        image: fitfashion-auth:latest 
        ports:
        - containerPort: 8001
        env:
        - name: SECRET_KEY
          value: "remivichicoke" 
        - name: DEBUG
          value: "False"
        - name: DJANGO_ALLOWED_HOSTS
          value: "ms-auth-service,localhost,127.0.0.1" 
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /auth/users/me/ 
            port: 8001
          initialDelaySeconds: 15
          timeoutSeconds: 5
        
        volumeMounts:
        - name: auth-db-storage
          mountPath: /app/db.sqlite3 
          subPath: db.sqlite3
      volumes:
      - name: auth-db-storage
        persistentVolumeClaim:
          claimName: ms-auth-pvc